# Generated by Django 6.1.1 on 2026-09-15 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_deleted_message_replied_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hidden_user')},
            },
        ),
    ]
