# Generated by Django 6.1.1 on 2026-09-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_hiddenchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiddenChat',
        ),
    ]
